---
sudo: false
language: ruby
cache: bundler
dist: trusty
git:
  depth: 1
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
before_install:
  - gem update --system
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
