---
sudo: false
language: ruby
cache: bundler
dist: trusty
git:
  depth: 1
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - jruby-head
  - ruby-head
  - rbx-3
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-3
before_install:
  - gem update --system
  - gem install bundler -v 2.0.1
